---
name: CI/CD

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

permissions:
  contents: read
  pull-requests: read
  checks: write
  packages: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup project
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.3"

      - name: Lint project
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60

  build:
    name: Build
    needs: lint
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get short SHA
        id: vars
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build Docker Image
        run: docker build -t ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.short_sha }} .

      - name: Push Docker Image to Github Container Registry
        run: docker push ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.short_sha }}
