---
name: CI/CD

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

permissions:
  contents: read
  pull-requests: read
  checks: write
  packages: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup project
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.3"
      - name: Lint project
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60

  build-and-push:
    name: Build and Push
    runs-on: ubuntu-24.04
    needs: lint
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .
          docker build -t ghcr.io/${{ github.repository }}:${{ github.sha }} .
      - name: Push Docker Image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:${{ github.sha }}

  deploy:
    name: Deploy
    runs-on: ubuntu-24.04
    needs: build-and-push
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Connect to server and deploy container
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          IMAGE_NAME: ghcr.io/${{ github.repository }}:${{ github.sha }}
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
            sudo docker rm -vf $(docker ps -aq)
            sudo docker rmi -f $(docker images -aq)
            sudo docker pull ghcr.io/${{ github.repository }}:${{ github.sha }}
            sudo docker run --name placelists-back -p 8080:8080 ghcr.io/${{ github.repository }}:${{ github.sha }}
          EOF
