---
name: CI/CD

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

permissions:
  contents: read
  pull-requests: read
  checks: write
  packages: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup project
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.3"
      - name: Lint project
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60

  build-and-push:
    name: Build and Push
    runs-on: ubuntu-24.04
    needs: lint
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .
          docker build -t ghcr.io/${{ github.repository }}:${{ github.sha }} .
      - name: Push Docker Image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:${{ github.sha }}

  deploy:
    name: Deploy
    runs-on: ubuntu-24.04
    needs: build-and-push
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker system prune -f
            sudo docker pull ghcr.io/${{ github.repository }}:${{ github.sha }}
            sudo docker run -p 8080:8080 ghcr.io/${{ github.repository }}:${{ github.sha }}
