---
name: Lint

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  lint:
    name: lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.3"
      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
